### ISSUE TITLE
[다크모드 화면 이슈] 색상

### ISSUE THREAD

**Issue by jiwoochris** [ai-surfers/pocket-prompt-frontend#44]
### 🗒️ Description
다크모드로 볼 때 화면이 이렇게 보입니다.

### ✅ To-do

- [ ] ???

![image](https://github.com/user-attachments/assets/b10aa9b1-9e45-4820-b121-c343b80d02a5)

**Comment by hailey-hy** [comment]
https://github.com/ai-surfers/pocket-prompt-frontend/pull/59 에서 해결되었습니다!
